<script src="{{ url('../assets/libs/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url('../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url('../assets/libs/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url('../assets/libs/feather-icons/dist/feather.min.js') }}"></script>
<script src="{{ url('../assets/libs/prismjs/components/prism-core.min.js') }}"></script>
<script src="{{ url('../assets/libs/prismjs/components/prism-markup.min.js') }}"></script>
<script src="{{ url('../assets/libs/prismjs/plugins/line-numbers/prism-line-numbers.min.js') }}"></script>
<script src="{{ url('../assets/libs/apexcharts/dist/apexcharts.min.js') }}"></script>
<script src="{{ url('../assets/libs/dropzone/dist/min/dropzone.min.js') }}"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
